name: Deploy React app to SiteGround

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Show local build contents
        run: |
          echo ">>> Local build listing"
          ls -la dist || (echo "No build folder found" && exit 1)

      - name: Upload build files via SCP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SG_HOST }}
          username: ${{ secrets.SG_USER }}
          key: ${{ secrets.SG_KEY }}
          port: ${{ secrets.SG_PORT }}
          script: |
            mkdir -p /home/${{ secrets.SG_USER }}/domains/ramsescubidev.com/public_html
        env:
          DIST_DIR: dist
        run: |
          tar czf dist.tar.gz -C $DIST_DIR .
          scp -P ${{ secrets.SG_PORT }} dist.tar.gz ${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}:/home/${{ secrets.SG_USER }}/domains/ramsescubidev.com/public_html/
          ssh -i ~/.ssh/siteground_deploy -p ${{ secrets.SG_PORT }} ${{ secrets.SG_USER }}@${{ secrets.SG_HOST }} "cd /home/${{ secrets.SG_USER }}/domains/ramsescubidev.com/public_html && tar xzf dist.tar.gz && rm dist.tar.gz"

      - name: Verify remote files (ls)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SG_HOST }}
          username: ${{ secrets.SG_USER }}
          key: ${{ secrets.SG_KEY }}
          port: ${{ secrets.SG_PORT }}
          script: |
            echo "Remote pwd:"
            pwd
            echo "Listing domain public_html:"
            ls -la /home/${{ secrets.SG_USER }}/domains/ramsescubidev.com/public_html/
            echo "Head of index.html (if exists):"
            if [ -f /home/${{ secrets.SG_USER }}/domains/ramsescubidev.com/public_html/index.html ]; then
              head -n 20 /home/${{ secrets.SG_USER }}/domains/ramsescubidev.com/public_html/index.html
            else
              echo "index.html not found"
            fi
