name: Deploy app to SiteGround

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to SiteGround via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SG_HOST }}
          username: ${{ secrets.SG_USER }}
          key: ${{ secrets.SG_KEY }}
          port: ${{ secrets.SG_PORT }}
          script: |
            cd /home/${{ secrets.SG_USER }}/public_html
            rm -rf *           # Limpia el contenido anterior
            mkdir -p build
          # Subir los archivos build generados
      - name: Upload build files
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SG_HOST }}
          username: ${{ secrets.SG_USER }}
          key: ${{ secrets.SG_KEY }}
          port: ${{ secrets.SG_PORT }}
          source: "build/*"
          target: "/home/${{ secrets.SG_USER }}/public_html/"
